from pathlib import Path
from typing import Any, Protocol

from .diagnostics import DiagnosticsReport
from .models import ValidatorManifest


class ValidationRuleProtocol(Protocol):
    @property
    def name(self) -> str: ...

    def validate(self, target: Any, report: DiagnosticsReport) -> None: ...


class ManifestValidationEngineProtocol(Protocol):
    def validate_manifest(self, manifest_data: dict) -> DiagnosticsReport: ...
    def validate_component(self, component_dir: Path | str) -> DiagnosticsReport: ...
    def validate_directory(self, target_dir: Path | str) -> DiagnosticsReport: ...
    def validate_registry(self, registry_dir: Path | str) -> DiagnosticsReport: ...
    def validate_dependencies(self, manifest: ValidatorManifest) -> DiagnosticsReport: ...
