from pathlib import Path
from typing import Dict, List, Protocol

from engine.validator.models import ValidatorManifest


class RegistryBuilderProtocol(Protocol):
    def build_registry(self, source_dir: Path | str, output_dir: Path | str) -> Path: ...
    def build_indexes(self, manifests: List[ValidatorManifest]) -> Dict[str, dict]: ...
    def build_statistics(self, manifests: List[ValidatorManifest]) -> dict: ...
    def build_checksums(self, output_dir: Path | str) -> dict: ...
    def verify_registry(self, registry_dir: Path | str) -> bool: ...
    def clean_registry(self, registry_dir: Path | str) -> None: ...
