from typing import Protocol, Iterator
from pathlib import Path
from contextlib import contextmanager

class FileSystemTransactionProtocol(Protocol):
    def commit(self) -> None: ...
    def rollback(self) -> None: ...

class FileSystemProtocol(Protocol):
    def read_text(self, path: Path | str) -> str: ...
    def read_bytes(self, path: Path | str) -> bytes: ...
    def write_text_atomic(self, path: Path | str, content: str) -> None: ...
    def write_bytes_atomic(self, path: Path | str, content: bytes) -> None: ...
    def copy(self, src: Path | str, dst: Path | str) -> None: ...
    def move(self, src: Path | str, dst: Path | str) -> None: ...
    def delete(self, path: Path | str) -> None: ...
    def rename(self, src: Path | str, dst: Path | str) -> None: ...
    def exists(self, path: Path | str) -> bool: ...
    def create_directory(self, path: Path | str, parents: bool = True) -> None: ...
    def delete_directory(self, path: Path | str, recursive: bool = False) -> None: ...
    def is_symlink(self, path: Path | str) -> bool: ...
    def backup(self, path: Path | str) -> Path: ...
    def restore(self, backup_path: Path | str, original_path: Path | str) -> None: ...
    
    @contextmanager
    def transaction(self) -> Iterator[FileSystemTransactionProtocol]: ...
