from typing import Protocol, Optional
from pathlib import Path
from .models import Registry, ComponentManifest, PackManifest, RegistryMetadata

class RegistryProviderProtocol(Protocol):
    def get_registry(self) -> Registry: ...
    def get_component(self, slug: str) -> ComponentManifest: ...
    def get_manifest(self, slug: str) -> ComponentManifest: ...
    def download_component(self, slug: str, dest_dir: Path) -> Path: ...
    def download_pack(self, slug: str, dest_dir: Path) -> Path: ...
    def component_exists(self, slug: str) -> bool: ...
    def pack_exists(self, slug: str) -> bool: ...
    def health(self) -> bool: ...
    def metadata(self) -> RegistryMetadata: ...
    def version(self) -> str: ...
